@startuml

skinparam defaultFontName Segoe UI
skinparam Style strictuml
skinparam DefaultFontSize 16
skinparam ArrowThickness 2.2
skinparam ArrowColor #gray
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 60
skinparam SequenceMessageAlignment center

@enduml

@startuml
title "using hidden element for layout structuring"
skinparam Style strictuml
skinparam defaultFontName Segoe UI
skinparam DefaultFontSize 16
'skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.2
skinparam ArrowColor #gray
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 60
skinparam SequenceMessageAlignment center


'Collections
skinparam collections {
  'Font Style (inherits from Default)
  FontSize 14

  'Border Color
  BackgroundColor Green
  BorderColor Black
}

package "Core Components" {
    [Backend Client] as BackendClient
    [File Reader] as FileReader
    [Content Transform] as ContentTransform
    [Logging]
    collections Foo6
}



BackendClient ~~> ContentTransform : uses
FileReader ~~> ContentTransform: uses
BackendClient ~[hidden]~> Logging



@enduml

@startuml
title "switch off shadows"
skinparam defaultFontName Segoe UI
' Remove shadows
skinparam shadowing false

actor User
[Third party application] as ThirdPartyApp

package "Spring Boot Application" {
    rectangle Controllers <<Spring REST controllers>>
    rectangle DataStoreService <<Spring service>>
    rectangle Repository <<Spring repository>>
}

User --> Controllers
ThirdPartyApp --> Controllers

Controllers --> DataStoreService
DataStoreService --> Repository

@enduml

@startuml

skinparam defaultFontName Segoe UI
title "Keeping element togther"
actor User
[Third party application] as ThirdPartyApp

/' Try to keep PostgresDB and Mail together,
   so they are at the same level in the diagram. '/
together {
    [PostgreSQL database] as PostgresDB <<Database>>
    [Mail server] as Mail <<Mail server>>
}

package "Spring Boot Application" {
    [Controllers] <<Spring REST controllers>>
    [DataStoreService] <<Spring service>>
    [Repository] <<Spring repository>>
}

User --> Controllers
ThirdPartyApp --> Controllers

Controllers --> DataStoreService

DataStoreService --> Repository
DataStoreService --> Mail

Repository --> PostgresDB

@enduml


@startuml

title diagram in monochrome - %date%
' Generated diagram will be in black/grey/white.
skinparam monochrome true
skinparam defaultFontName Segoe UI

actor User
[Third party application] as ThirdPartyApp

package "Spring Boot Application" {
    rectangle Controllers <<Spring REST controllers>>
    rectangle DataStoreService <<Spring service>>
    rectangle Repository <<Spring repository>>
}

User --> Controllers
ThirdPartyApp --> Controllers

Controllers --> DataStoreService
DataStoreService --> Repository

@enduml


